/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_owls_jni_NativeCaller */

#ifndef _Included_org_owls_jni_NativeCaller
#define _Included_org_owls_jni_NativeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_owls_jni_NativeCaller
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_owls_jni_NativeCaller_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
